name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # 👇 Step 1: Create environment.prod.ts using GitHub Secret
      - name: Create environment.prod.ts
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: true,
            apiUrl: '${{ secrets.API_URL }}'
          };" > src/environments/environment.prod.ts

      # 👇 Step 2: Build Angular App
      - name: Build Angular app
        run: npm run build --configuration 

      # 👇 Step 3: Deploy (example for S3 / or your hosting target)
      # Replace this with your actual deploy command
      - name: Deploy to Server
        run: |
          echo "Deploy step here (e.g., upload dist/ to your hosting)"
