name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # ✅ Create both environment files dynamically (using GitHub Secrets)
      - name: Create environment files
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: false,
            api: '${{ secrets.DEV_API_URL }}',
            socketUrl: '${{ secrets.DEV_SOCKET_URL }}'
          };" > src/environments/environment.ts
          
          echo "export const environment = {
            production: true,
            api: '${{ secrets.PROD_API_URL }}',
            socketUrl: '${{ secrets.PROD_SOCKET_URL }}'
          };" > src/environments/environment.prod.ts

      - name: Build Angular app
        run: npm run build -- --configuration production

      # ✅ Deploy to EC2
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy dist folder to EC2
          scp -i private_key.pem -r dist/second-project-frontend/browser/* ${USER}@${HOST}:/var/www/angular/browser/

          # Restart nginx
          ssh -i private_key.pem ${USER}@${HOST} "sudo systemctl restart nginx"
