name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # ✅ Create both environment files dynamically using secrets
      - name: Create environment files
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: false,
            api: 'http://localhost:3000',
            socketUrl: 'http://localhost:3000',
            googleClientId: '${{ secrets.GOOGLE_CLIENT_ID }}',
            razorpayKey: '${{ secrets.RAZORPAY_KEY }}',
            adminId: '${{ secrets.ADMIN_ID }}',
            googleUrl: '${{ secrets.GOOGLE_URL }}',
            S3_BASE_URL: '${{ secrets.S3_BASE_URL }}'
          };" > src/environments/environment.ts
          
          echo "export const environment = {
            production: true,
            api: '${{ secrets.API_URL }}',
            socketUrl: '${{ secrets.SOCKET_URL }}',
            googleClientId: '${{ secrets.GOOGLE_CLIENT_ID }}',
            razorpayKey: '${{ secrets.RAZORPAY_KEY }}',
            adminId: '${{ secrets.ADMIN_ID }}',
            googleUrl: '${{ secrets.GOOGLE_URL }}',
            S3_BASE_URL: '${{ secrets.S3_BASE_URL }}'
          };" > src/environments/environment.prod.ts

      - name: Build Angular app
        run: npm run build -- --configuration production

      # 🔹 Example deploy step (adjust for your server)
      - name: Deploy to EC2
        run: |
          echo "Build complete — add your deploy script here."
